name: multiple_localization_example
description: Demonstrates how to use the multiple_localization plugin.

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.0
  multiple_localization:
    path: ../

dev_dependencies:
  innim_lint: ^0.5.0+1
  intl_translation: ^0.20.0
